name = "E1"
uuid = "c93e011b-2a58-47e8-b6fc-f93eb5ed2c2d"
authors = ["William96123 <duanbwilliam@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
